Vagrant.configure("2") do |config|

  config.vm.define "gateway", primary:true do |gateway|
      gateway.vm.box = "ubuntu/focal64"
      gateway.vm.hostname = "gateway"

      $scriptGatewayOnce = <<-'SCRIPT'
          echo 1 > /proc/sys/net/ipv4/ip_forward
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
          sudo apt-get update
          sudo apt-get install -y isc-dhcp-server
          sed -i 's/INTERFACESv4=""/INTERFACESv4="enp0s8"/g' /etc/default/isc-dhcp-server
          cp /vagrant/dhcpd.conf /etc/dhcp/dhcpd.conf
          service isc-dhcp-server restart
      SCRIPT

      gateway.vm.provision "gateway_once", type: "shell" do |fo|
        fo.inline = $scriptGatewayOnce
      end

      $scriptGatewayAlways = <<-'SCRIPT'
          iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
      SCRIPT

      gateway.vm.provision "gateway_always", type: "shell", run: "always" do |fo|
        fo.inline = $scriptGatewayAlways
      end

      gateway.vm.provision "conectividad", type: "shell",
        inline: "ping -c 2 google.com"

      # fachada.vm.network "public_network",
      #	use_dhcp_assigned_default_route: true
      gateway.vm.network "private_network", ip: "192.168.100.1",
        virtualbox__intnet: "lan"
      # fachada.vm.network "private_network", ip: "192.168.121.1",
        #            virtualbox__intnet: "dmz"
  end

  #Para levantar la maquina se requiere vagrant up lan
  config.vm.define "lan", autostart:false do |lan|

    lan.vm.box = "ubuntu/focal64"
	lan.vm.hostname = "lan"

	$scriptGateway = <<-'SCRIPT'
	    # No salir a internet por enp0s3 de NAT Vagrant
      ip r del default via 10.0.2.2

      # Quitar al activar DHCP ---
#      ip r add default via 192.168.100.1
#      rm /etc/resolv.conf
#      echo "nameserver 1.1.1.1" >/etc/resolv.conf
#      echo "nameserver 8.8.8.8" >>/etc/resolv.conf
      # Quitar al activar DHCP ---

      echo Comprobar conectividad gateway...
      ping -c 2 192.168.100.1
      echo Comprobar conectividad Google...
      ping -c 2 www.google.com
      #traceroute a google
  	SCRIPT

	lan.vm.provision "lan_all", type: "shell", run: "always" do |lgw|
          lgw.inline = $scriptGateway
    end
	
	 lan.vm.network "private_network", type: "dhcp",
	   	virtualbox__intnet: "lan"
#	lan.vm.network "private_network", ip: "192.168.100.2",
#		virtualbox__intnet: "lan"
  end

# $script = <<-'SCRIPT'
# iptables -I OUTPUT -o enp0s3 -j DROP
# iptables -I INPUT -i enp0s3 -j DROP
# iptables -I INPUT -i enp0s3 -p tcp --dport 22 -j ACCEPT
# iptables -I OUTPUT -o enp0s3 -p tcp --sport 22 -j ACCEPT
# iptables -I OUTPUT -o lo -j ACCEPT
# iptables -I INPUT -i lo -j ACCEPT
# rm /etc/resolv.conf
# echo "nameserver 1.1.1.1" >/etc/resolv.conf
# echo "nameserver 8.8.8.8" >>/etc/resolv.conf
# SCRIPT

#    $scriptAlways = <<-'SCRIPT'
#    sudo ip r del default via 10.0.2.2
#    echo 1 > /proc/sys/net/ipv4/ip_forward
#    SCRIPT

# config.vm.provision "todas", type: "shell" do |s|
#    s.inline = $script
#  end

#  config.vm.provision "todas_siempre", type: "shell",
#	run: "always" do |ts|
#    ts.inline = $scriptAlways
#  end

#  config.vm.synced_folder "./", "/vagrant_data"

end
